# Generated by Django 2.2.3 on 2019-10-14 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtVirtualLinkInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NsLcmOpOcc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operationState', models.TextField(default='PROCESSING')),
                ('statusEnteredTime', models.DateTimeField()),
                ('nsInstanceId', models.TextField()),
                ('lcmOperationType', models.TextField()),
                ('startTime', models.DateField(auto_now_add=True)),
                ('isAutomaticInvocation', models.BooleanField()),
                ('operationParams', models.TextField(blank=True, null=True)),
                ('isCancelPending', models.BooleanField()),
                ('cancelMode', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceChanges',
            fields=[
                ('resourceChanges', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resourceChanges', serialize=False, to='NSLCMOperationOccurrences.NsLcmOpOcc')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedVnf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vnfInstanceId', models.TextField()),
                ('vnfdId', models.TextField()),
                ('vnfProfileId', models.TextField()),
                ('vnfName', models.TextField()),
                ('changeType', models.TextField()),
                ('changeResult', models.TextField()),
                ('affectedVnfs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectedVnfs', to='NSLCMOperationOccurrences.ResourceChanges')),
            ],
        ),
        migrations.CreateModel(
            name='ChangedInfo',
            fields=[
                ('changedInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='changedInfo', serialize=False, to='NSLCMOperationOccurrences.AffectedVnf')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='_links', serialize=False, to='NSLCMOperationOccurrences.NsLcmOpOcc')),
                ('link_self', models.URLField()),
                ('nsInstance', models.URLField()),
                ('cancel', models.URLField(blank=True, null=True)),
                ('retry', models.URLField(blank=True, null=True)),
                ('rollback', models.URLField(blank=True, null=True)),
                ('_continue', models.URLField(blank=True, null=True)),
                ('fail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimId', models.TextField(blank=True, null=True)),
                ('resourceProviderId', models.TextField(blank=True, null=True)),
                ('resourceId', models.TextField()),
                ('vimLevelResourceType', models.TextField(blank=True, null=True)),
                ('resourceHandle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resourceHandle', to='NSLCMOperationOccurrences.ExtVirtualLinkInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExtLinkPortInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpInstanceId', models.TextField(blank=True, null=True)),
                ('extLinkPorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extLinkPorts', to='NSLCMOperationOccurrences.ExtVirtualLinkInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ModifyVnfInfoData',
            fields=[
                ('changedVnfInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='changedVnfInfo', serialize=False, to='NSLCMOperationOccurrences.ChangedInfo')),
                ('vnfInstanceId', models.TextField()),
                ('vnfInstanceName', models.TextField(blank=True, null=True)),
                ('vnfInstanceDescription', models.TextField(blank=True, null=True)),
                ('vnfdId', models.TextField(blank=True, null=True)),
                ('vnfConfigurableProperties', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('extensions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='extvirtuallinkinfo',
            name='changedExtConnectivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changedExtConnectivity', to='NSLCMOperationOccurrences.ChangedInfo'),
        ),
        migrations.CreateModel(
            name='AffectedVnffg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vnffgInstanceId', models.TextField()),
                ('vnffgdId', models.TextField()),
                ('changeType', models.TextField()),
                ('changeResult', models.TextField()),
                ('affectedVnffg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectedVnffg', to='NSLCMOperationOccurrences.ResourceChanges')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedVirtualLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nsVirtualLinkInstanceId', models.TextField()),
                ('nsVirtualLinkDescId', models.TextField()),
                ('vlProfileId', models.TextField()),
                ('changeType', models.TextField()),
                ('changeResult', models.TextField()),
                ('affectedVl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectedVl', to='NSLCMOperationOccurrences.ResourceChanges')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedSap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sapInstanceId', models.TextField()),
                ('sapdId', models.TextField()),
                ('sapName', models.TextField()),
                ('changeType', models.TextField()),
                ('changeResult', models.TextField()),
                ('affectedSaps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectedSaps', to='NSLCMOperationOccurrences.ResourceChanges')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedNs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nsInstanceId', models.TextField()),
                ('nsdId', models.TextField()),
                ('changeType', models.TextField()),
                ('changeResult', models.TextField()),
                ('affectedNss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectedNss', to='NSLCMOperationOccurrences.ResourceChanges')),
            ],
        ),
    ]
