# Generated by Django 2.2 on 2020-04-02 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FmSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callbackUri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FmSubscriptionLink',
            fields=[
                ('_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                related_name='fm_subscription_fk_fm_subscription_link', serialize=False,
                                                to='NSFaultSubscription.FmSubscription')),
                ('link_self', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FmSubscriptionsFilter',
            fields=[
                ('filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                related_name='fm_subscription_fk_fm_subscriptions_filter',
                                                serialize=False, to='NSFaultSubscription.FmSubscription')),
                ('notificationTypes', models.CharField(blank=True, choices=[('AlarmNotification', 'AlarmNotification'),
                                                                            ('AlarmClearedNotification',
                                                                             'AlarmClearedNotification'), (
                                                                            'AlarmListRebuiltNotification',
                                                                            'AlarmListRebuiltNotification')],
                                                       max_length=30, null=True)),
                ('faultyResourceTypes', models.CharField(blank=True,
                                                         choices=[('COMPUTE', 'COMPUTE'), ('STORAGE', 'STORAGE'),
                                                                  ('NETWORK', 'NETWORK')], max_length=30, null=True)),
                ('perceivedSeverities', models.CharField(blank=True,
                                                         choices=[('CRITICAL', 'CRITICAL'), ('MAJOR', 'MAJOR'),
                                                                  ('MINOR', 'MINOR'), ('WARNING', 'WARNING'),
                                                                  ('INDETERMINATE', 'INDETERMINATE'),
                                                                  ('CLEARED', 'CLEARED')], max_length=30, null=True)),
                ('eventTypes', models.CharField(blank=True, choices=[('COMMUNICATIONS_ALARM', 'COMMUNICATIONS_ALARM'), (
                'PROCESSING_ERROR_ALARM', 'PROCESSING_ERROR_ALARM'), ('ENVIRONMENTAL_ALARM', 'ENVIRONMENTAL_ALARM'),
                                                                     ('QOS_ALARM', 'QOS_ALARM'),
                                                                     ('EQUIPMENT_ALARM', 'EQUIPMENT_ALARM')],
                                                max_length=30, null=True)),
                ('probableCauses', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NsInstanceSubscriptionFilter',
            fields=[
                ('nsInstanceSubscriptionFilter',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                      related_name='fm_subscription_filter_fk_ns_instance_subscription_filter',
                                      serialize=False, to='NSFaultSubscription.FmSubscriptionsFilter')),
                ('nsdIds', models.TextField(blank=True, null=True)),
                ('vnfdIds', models.TextField(blank=True, null=True)),
                ('pnfdIds', models.TextField(blank=True, null=True)),
                ('nsInstanceIds', models.TextField(blank=True, null=True)),
                ('nsInstanceNames', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
