# Generated by Django 2.2 on 2020-08-21 09:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PkgmNotificationsProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnfProductName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PkgmNotificationsProviders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnfProvider', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PkgmSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callbackUri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PkgmNotificationsFilter',
            fields=[
                ('filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                related_name='pkgm_subscription_fk_filter', serialize=False,
                                                to='VnfPackageSubscription.PkgmSubscription')),
                ('notificationTypes', models.TextField(blank=True, null=True)),
                ('vnfdId', models.TextField(blank=True, null=True)),
                ('vnfPkgId', models.TextField(blank=True, null=True)),
                ('operationalState', models.TextField(blank=True, null=True)),
                ('usageState', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PkgmSubscriptionLink',
            fields=[
                ('_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                related_name='pkgm_subscription_fk_links', serialize=False,
                                                to='VnfPackageSubscription.PkgmSubscription')),
                ('link_self', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PkgmNotificationsVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnfSoftwareVersion', models.TextField()),
                ('vnfdVersions', models.TextField(blank=True, null=True)),
                ('versions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='pkgm_notifications_products_fk_versions',
                                               to='VnfPackageSubscription.PkgmNotificationsProducts')),
            ],
        ),
        migrations.AddField(
            model_name='pkgmnotificationsproducts',
            name='vnfProducts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='pkgm_notifications_providers_fk_products',
                                    to='VnfPackageSubscription.PkgmNotificationsProviders'),
        ),
        migrations.AddField(
            model_name='pkgmnotificationsproviders',
            name='vnfProductsFromProviders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='pkgm_notifications_fk_providers',
                                    to='VnfPackageSubscription.PkgmNotificationsFilter'),
        ),
    ]
