# Generated by Django 2.2.3 on 2019-09-28 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NsdInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nsdId', models.TextField(blank=True, null=True)),
                ('nsdName', models.TextField(blank=True, null=True)),
                ('nsdVersion', models.TextField(blank=True, null=True)),
                ('nsdDesigner', models.TextField(blank=True, null=True)),
                ('nsdInvariantId', models.TextField(blank=True, null=True)),
                ('vnfPkgIds', models.TextField(blank=True, null=True)),
                ('pnfdInfoIds', models.TextField(blank=True, null=True)),
                ('nestedNsdInfoIds', models.TextField(blank=True, null=True)),
                ('nsdOnboardingState', models.TextField(default='CREATED')),
                ('nsdOperationalState', models.TextField(default='DISABLED')),
                ('nsdUsageState', models.TextField(default='NOT_IN_USE')),
                ('userDefinedData', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NsdInfoLinks',
            fields=[
                ('_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                related_name='nsd_info_fk_link', serialize=False,
                                                to='NSDManagement.NsdInfo')),
                ('link_self', models.URLField()),
                ('nsd_content', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NsdInfoProblemDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('detail', models.TextField()),
                ('instance', models.URLField(blank=True, null=True)),
                ('onboardingFailureDetails',
                 models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      related_name='nsd_info_fk_problem_details', to='NSDManagement.NsdInfo')),
            ],
        ),
    ]
