# Generated by Django 2.2 on 2020-04-02 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('managedObjectId', models.TextField()),
                ('alarmRaisedTime', models.TimeField(auto_now_add=True)),
                ('alarmChangedTime', models.TimeField(blank=True, null=True)),
                ('alarmClearedTime', models.TimeField(blank=True, null=True)),
                ('alarmAcknowledgedTime', models.TimeField(blank=True, null=True)),
                ('ackState',
                 models.CharField(choices=[('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('UNACKNOWLEDGED', 'UNACKNOWLEDGED')],
                                  default='UNACKNOWLEDGED', max_length=20)),
                ('perceivedSeverity', models.CharField(
                    choices=[('CRITICAL', 'CRITICAL'), ('MAJOR', 'MAJOR'), ('MINOR', 'MINOR'), ('WARNING', 'WARNING'),
                             ('INDETERMINATE', 'INDETERMINATE'), ('CLEARED', 'CLEARED')], default='CRITICAL',
                    max_length=20)),
                ('eventTime', models.TimeField(auto_now_add=True)),
                ('eventType', models.CharField(choices=[('COMMUNICATIONS_ALARM', 'COMMUNICATIONS_ALARM'),
                                                        ('PROCESSING_ERROR_ALARM', 'PROCESSING_ERROR_ALARM'),
                                                        ('ENVIRONMENTAL_ALARM', 'ENVIRONMENTAL_ALARM'),
                                                        ('QOS_ALARM', 'QOS_ALARM'),
                                                        ('EQUIPMENT_ALARM', 'EQUIPMENT_ALARM')],
                                               default='PROCESSING_ERROR_ALARM', max_length=30)),
                ('faultType', models.TextField(blank=True, null=True)),
                ('probableCause', models.TextField(blank=True, null=True)),
                ('isRootCause', models.BooleanField(default=False)),
                ('correlatedAlarmIds', models.TextField(blank=True, null=True)),
                ('faultDetails', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultyResourceInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faultyResourceType', models.CharField(blank=True,
                                                        choices=[('COMPUTE', 'COMPUTE'), ('STORAGE', 'STORAGE'),
                                                                 ('NETWORK', 'NETWORK')], default='COMPUTE',
                                                        max_length=10, null=True)),
                ('rootCauseFaultyResource',
                 models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      related_name='alarm_fk_root_cause_faulty_resource',
                                      to='NSFaultManagement.Alarm')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmLinks',
            fields=[
                ('_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                related_name='alarm_fk_link', serialize=False,
                                                to='NSFaultManagement.Alarm')),
                ('link_self', models.URLField()),
                ('objectInstance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceHandle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vimId', models.TextField(blank=True, null=True)),
                ('resourceProviderId', models.TextField(blank=True, null=True)),
                ('resourceId', models.TextField()),
                ('vimLevelResourceType', models.TextField(blank=True, null=True)),
                ('faultyResource',
                 models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      related_name='faulty_resource_info_fk_resource_handle',
                                      to='NSFaultManagement.FaultyResourceInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FaultyComponentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faultyNestedNsInstanceId', models.UUIDField(blank=True, null=True)),
                ('faultyNsVirtualLinkInstanceId', models.TextField(blank=True, null=True)),
                ('faultyVnfInstanceId', models.TextField(blank=True, null=True)),
                ('rootCauseFaultyComponent',
                 models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                      related_name='alarm_fk_root_cause_faulty_component',
                                      to='NSFaultManagement.Alarm')),
            ],
        ),
    ]
