# Generated by Django 4.2.8 on 2026-03-02 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MecAppInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mecAppInstanceName', models.TextField()),
                ('mecAppInstanceDescription', models.TextField(blank=True, null=True)),
                ('mecAppType', models.TextField(default='GENERAL')),
                ('namespace', models.TextField(default='default')),
                ('deploymentState', models.TextField(default='NOT_INSTANTIATED')),
                ('yamlContent', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mec_app_instance',
                'ordering': ['-createdAt'],
            },
        ),
    ]
