# Generated by Django 2.2.3 on 2019-08-21 03:52


from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LccnSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callbackUri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LccnSubscriptionLink',
            fields=[
                ('_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                related_name='lccn_subscription_fk_links', serialize=False,
                                                to='NSLifecycleSubscriptions.LccnSubscription')),
                ('link_self', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LifecycleChangeNotificationsFilter',
            fields=[
                ('filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                related_name='lccn_subscription_fk_filter', serialize=False,
                                                to='NSLifecycleSubscriptions.LccnSubscription')),
                ('notificationTypes', models.TextField(blank=True, null=True)),
                ('operationTypes', models.TextField(blank=True, null=True)),
                ('operationStates', models.TextField(blank=True, null=True)),
                ('nsComponentTypes', models.TextField(blank=True, null=True)),
                ('lcmOpNameImpactingNsComponent', models.TextField(blank=True, null=True)),
                ('lcmOpOccStatusImpactingNsComponent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NsInstanceSubscriptionFilter',
            fields=[
                ('nsInstanceSubscriptionFilter',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                      related_name='lccn_subscription_filter_fk_filter', serialize=False,
                                      to='NSLifecycleSubscriptions.LifecycleChangeNotificationsFilter')),
                ('nsdIds', models.TextField(blank=True, null=True)),
                ('vnfdIds', models.TextField(blank=True, null=True)),
                ('pnfdIds', models.TextField(blank=True, null=True)),
                ('nsInstanceIds', models.TextField(blank=True, null=True)),
                ('nsInstanceNames', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
