# Generated by Django 4.2.8 on 2026-02-26 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GnbInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gnbInstanceName', models.TextField()),
                ('gnbInstanceDescription', models.TextField(blank=True, null=True)),
                ('namespace', models.TextField(default='default')),
                ('deploymentState', models.TextField(default='NOT_INSTANTIATED')),
                ('yamlContent', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
