# Generated by Django 4.2.8 on 2026-04-02 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GnbManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnbTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('templateName', models.TextField()),
                ('templateDescription', models.TextField(blank=True, null=True)),
                ('namespace', models.TextField(default='default')),
                ('yamlContent', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
