# Generated by Django 4.2.8 on 2026-04-04 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GnbManagement', '0002_gnbtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UeInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ueInstanceName', models.TextField()),
                ('ueInstanceDescription', models.TextField(blank=True, null=True)),
                ('namespace', models.TextField(default='default')),
                ('deploymentState', models.TextField(default='NOT_INSTANTIATED')),
                ('yamlContent', models.TextField()),
                ('gnbServiceName', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ue_instance',
                'ordering': ['-createdAt'],
            },
        ),
    ]
