# File: upfcfg.conf
version: 1.0.3
description: UPF configuration

pfcp:
  addr: upf-330436be-svc
  nodeID: upf-330436be-svc
  retransTimeout: 1s
  maxRetrans: 3

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: upf-330436be-svc
      type: N3

dnnList:
  - dnn: internet
    cidr: 60.60.0.0/24

logger:
  enable: true
  level: info
  reportCaller: false
